version: "3.9"

services:
  web:
    build: ./web
    image: my_web
    container_name: web_projet
    ports:
      - 80:80
  back:
    build: ./back
    image: malikh551/back_node
    container_name: back_projet
    ports:
      - 3000:4000
  bdd:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
      - dbconfig:/data/configdb

volumes:
  dbdata: {}
  dbconfig: {}
