version: "3.9"

services:
  web:
    build: ./web
    image: malikh551/front_node
    container_name: web_projet
    ports:
      - 80:80
  back:
    build: ./back
    image: malikh551/back_node
    container_name: back_projet
    ports:
      - 4000:4000
  bdd:
    image: mongo
    restart: always
    container_name: db_projet
    environment:
        MONGO_INITDB_DATABASE: app
    volumes:
      - dbdata:/data/db
      - dbconfig:/data/configdb
      - ./bdd/init.js:/docker-entrypoint-initdb.d/init.js

volumes:
  dbdata: {}
  dbconfig: {}
